security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User\User
                property: email

    firewalls:
        # Disable security for dev assets
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # All /api routes (including login_check)
        api:
            pattern:   ^/api
            stateless: true
            lazy: true
            provider:  app_user_provider
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure



            # 2) Protect /api/** with JWT on subsequent calls
            jwt: ~

        # Your normal “web” firewall
        main:
            lazy:     true
            provider: app_user_provider
            # form_login, logout, etc. go here

    access_control:
        # allow anonymous POST to login_check
        - { path: ^/api/login_check, roles: PUBLIC_ACCESS }
        # require JWT from the rest of /api
        - { path: ^/api,              roles: IS_AUTHENTICATED_FULLY }
